import type { Metadata } from "next"
import "./globals.css"
import Navbar from "@/components/navbar/Navbar"
import MobileNav from "@/components/navbar/MobileNav"
import Footer from "@/components/footer/Footer"
import { ReduxProvider } from "@/redux/provider"
import { ToastContainer } from "react-toastify"
import "react-toastify/dist/ReactToastify.css"

export const metadata: Metadata = {
  title: "DEPT. CSE PIT",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <ToastContainer
            theme="colored"
            newestOnTop
            draggable={false}
            toastStyle={{ background: "#00a384", color: "black" }}
          />
          <Navbar />
          <MobileNav />

          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  )
}
