import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Navbar from "@/components/navbar/Navbar"
import MobileNav from "@/components/navbar/MobileNav"
import Footer from "@/components/footer/Footer"
import { ReduxProvider } from "@/redux/provider"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "DEPT. CSE PIT",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <Navbar />
          <MobileNav />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  )
}
